### ISSUE TITLE
[需要帮助] 请问GIMAP.png这个图片最新的版本现在要怎么获取？

### ISSUE THREAD

**Issue by 1004452714** [GengGode/cvAutoTrack#112]
现在在用的图片版本还是在须弥，在别的项目上注释来找的，实在没找到这个文件，可以帮我一下吗？
![image](https://github.com/GengGode/cvAutoTrack/assets/28773469/ccfb023a-966f-4bb2-b52c-36a53323282c)

![image](https://github.com/GengGode/cvAutoTrack/assets/28773469/2d2ba43b-b208-4086-aae2-4cc8e2cfa96f)

**Comment by GengGode** [comment]
处于githu策略和版权问题，不再将图片二进制放在库中，建议手动捷豹获取，有拼接代码可供参考
如果有需要，可以加入群717355752联系
