### ISSUE TITLE
后续开发计划

### ISSUE THREAD

**Issue by Sallee1** [GengGode/cvAutoTrack#14]
* 实现日志超过指定大小自动删除
* 实现在日志中写入系统信息
* 在局部追踪中添加重试机制，以提高局部追踪的稳定性
* 尝试适配带鱼屏

**Comment by GengGode** [comment]
[feat:实现日志文件大小上限](https://github.com/GengGode/cvAutoTrack/commit/3aa74cbe2414424795582d746b9cbca8cce7ef46)
[feat:日志中添加系统信息](https://github.com/GengGode/cvAutoTrack/commit/08dc32a150818ceeefd4f4a7a4977583c322966a)
[feat:添加如果局部匹配失败的一次重试匹配](https://github.com/GengGode/cvAutoTrack/commit/8a3d70f7c1b3f6e6a37b59b1a91b2d40cf81ebcc)
[fix:还原派蒙搜索匹配函数，修复带鱼屏无法正常使用问题](https://github.com/GengGode/cvAutoTrack/commit/6432fdde5171d1e46656398972a41588c841c0fc)
