### ISSUE TITLE
大小地图匹配很多错误匹配，即[0, 0]结果正常嘛

### ISSUE THREAD

**Issue by Alex-Beng** [GengGode/cvAutoTrack#80]
加了一个pos的实时输出，似乎观测，即大小地图匹配得到的pos，在我这是混杂在一堆false结果，[0,0]里面。

是我cvat帧率太低的问题嘛

![image](https://github.com/GengGode/cvAutoTrack/assets/30763045/e9a439e2-7412-4212-af8a-449dfb61a39a)

**Comment by GengGode** [comment]
不正常，目前匹配部分逻辑调整了但没调整完，匹配不上就会00，修修修
